const features = [
  {
    title: "AI Roadmaps",
    description: "Personalized learning paths generated by AI.",
  },
  {
    title: "Project-Based Learning",
    description: "Learn with hands-on real-world projects.",
  },
  {
    title: "Smart Mentorship",
    description: "Adaptive guidance based on your progress.",
  },
];

export default function Features() {
  return (
    <section className="bg-black px-6 py-28 text-white">

      <div className="mx-auto max-w-7xl">

        <div className="text-center">
          <h2 className="text-4xl font-bold md:text-6xl">
            Why Mentora?
          </h2>

          <p className="mx-auto mt-6 max-w-2xl text-lg text-gray-400">
            Personalized AI-powered learning built for modern students.
          </p>
        </div>

        <div className="mt-20 grid gap-8 md:grid-cols-3">

          {features.map((feature, index) => (
            <div
              key={index}
              className="group rounded-3xl border border-gray-800 bg-gradient-to-b from-gray-900 to-black p-8 transition duration-300 hover:-translate-y-2 hover:border-gray-600"
            >

              <div className="mb-6 h-14 w-14 rounded-2xl bg-white/10"></div>

              <h3 className="text-2xl font-semibold">
                {feature.title}
              </h3>

              <p className="mt-4 leading-relaxed text-gray-400">
                {feature.description}
              </p>

            </div>
          ))}

        </div>

      </div>

    </section>
  );
}